[package]
name = "faancit-wasm"
version = "0.1.0"
edition = "2024"
rust-version = "1.97"
description = "Cantonese faancit converter for WebAssembly"
repository = "https://github.com/wongws11/faancit-wasm"

[lib]
crate-type = ["cdylib", "rlib"]

[build-dependencies]
serde = { version = "=1.0.228", features = ["derive"] }
serde_json = "=1.0.150"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = "symbols"
